"""Actualizacion de tablas db

Revision ID: 918fc70f6ee7
Revises: 
Create Date: 2026-03-13 23:35:16.448059

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '918fc70f6ee7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle_pedido', schema=None) as batch_op:
        batch_op.alter_column('cantidad',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('subtotal',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)

    with op.batch_alter_table('detalle_pedido', schema=None) as batch_op:
        batch_op.alter_column('subtotal',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('cantidad',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
